name: JMeter Load Test

on:
  push:
    branches:
      - main

jobs:
  jmeter:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name:  Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install Azure CLI
      run: |
        curl -sL https://aka.ms/InstallAzureCLIDeb | sudo bash
        az --version

    - name: Set Azure Cloud Environment
      run: |
        az cloud set --name AzureCloud

    - name: Azure Login
      uses: azure/login@v1
      with:
        client-id: 9135a6c7-13df-4d13-b920-1da66af6b27e
        tenant-id: 6a2e5dc4-b83f-4fe6-9dd5-616bf3f0aa34
        audience: api://AzureADTokenExchange
        enable-AzPSSession: false
        environment: AzureCloud
        allow-no-subscriptions: true

    - name: Set Azure Subscription
      run: |
        az account set --subscription f246b020-dc38-4d48-93ee-e968a8c961dd

    - name: Create Resource Group
      run: |
        az group create --name myResourceGroup --location eastus

    - name: Create AKS Cluster
      run: |
        az aks create --resource-group myResourceGroup --name myAKSCluster --node-count 3 --enable-addons monitoring --generate-ssh-keys

    - name: Get AKS Credentials
      run: |
        az aks get-credentials --resource-group myResourceGroup --name myAKSCluster

    - name: Deploy JMeter Master and Slaves
      run: |
        kubectl apply -f jmeter-master-deployment.yaml
        kubectl apply -f jmeter-slave-deployment.yaml

    - name: Trigger JMeter Test
      run: |
        kubectl exec -it $(kubectl get pods -l "app=jmeter,role=master" -o jsonpath="{.items[0].metadata.name}") -- /bin/bash /opt/apache-jmeter-5.3/bin/jmeter -n -t /opt/apache-jmeter-5.3/test-plan.jmx -R $(kubectl get pods -l "app=jmeter,role=slave" -o jsonpath="{.items[*].status.podIP}" | sed 's/ /,/g')
